Linear Actuator Files
MissouriMRR/IARC-2020 pull request #152
Opened 2020-03-06 00:16 UTC by SercanAkcayMST

Closes #78

2020-03-06 17:31 UTC, ClayMav requested changes
Can't approve until i run it on my machine to test it.

2020-03-06 17:31 UTC, ClayMav commented on flight/utils/Wrapped_LAC.py
> +      return True
Move the checks for mechstop to the init function, and return nothing from this function

2020-03-06 17:31 UTC, ClayMav commented on flight/utils/Wrapped_LAC.py
> +from lac import *
don't use `import *` just import each of the individual elements used

2020-03-06 17:31 UTC, ClayMav commented on flight/utils/Wrapped_LAC.py
> +import asyncio
is this used

2020-03-06 17:31 UTC, ClayMav commented on flight/utils/Wrapped_LAC.py
> +#!/usr/bin/python
this should never be called so remove the shebang

2020-03-06 17:31 UTC, ClayMav commented on flight/utils/Wrapped_LAC.py
> +from mavsdk import System
Never used

2020-03-06 17:32 UTC, SercanAkcayMST commented
Got it I’ll make the changes

On Fri, Mar 6, 2020 at 11:31 AM Clay McGinnis <notifications@github.com>
wrote:

> *@ClayMav* requested changes on this pull request.
>
> Can't approve until i run it on my machine to test it.
> ------------------------------
>
> In flight/utils/Wrapped_LAC.py
> <https://github.com/MissouriMRR/IARC-2020/pull/152#discussion_r389039218>:
>
> > +    #Ensures the LAC will not hit mechanical stops
> +    if (rPosition <= rMechStop):
> +      return False
> +    elif (ePosition >= eMechStop):
> +      return False
> +    else:
> +      return True
>
> Move the checks for mechstop to the init function, and return nothing from
> this function
> ------------------------------
>
> In flight/utils/Wrapped_LAC.py
> <https://github.com/MissouriMRR/IARC-2020/pull/152#discussion_r389039986>:
>
> > @@ -0,0 +1,137 @@
> +#!/usr/bin/python
> +import asyncio
> +from lac import *
>
> don't use import * just import each of the individual elements used
> ------------------------------
>
> In flight/utils/Wrapped_LAC.py
> <https://github.com/MissouriMRR/IARC-2020/pull/152#discussion_r389040079>:
>
> > @@ -0,0 +1,137 @@
> +#!/usr/bin/python
> +import asyncio
>
> is this used
> ------------------------------
>
> In flight/utils/Wrapped_LAC.py
> <https://github.com/MissouriMRR/IARC-2020/pull/152#discussion_r389040179>:
>
> > @@ -0,0 +1,137 @@
> +#!/usr/bin/python
>
> this should never be called so remove the shebang
> ------------------------------
>
> In flight/utils/Wrapped_LAC.py
> <https://github.com/MissouriMRR/IARC-2020/pull/152#discussion_r389040352>:
>
> > @@ -0,0 +1,137 @@
> +#!/usr/bin/python
> +import asyncio
> +from lac import *
> +from mavsdk import System
>
> Never used
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MissouriMRR/IARC-2020/pull/152?email_source=notifications&email_token=AOSS5J4B74UNUKTGJTUZC43RGEXOJA5CNFSM4LCVO5NKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCYKVRPA#pullrequestreview-370497724>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOSS5J44DJ4WCO3VOQ4MIILRGEXOJANCNFSM4LCVO5NA>
> .
>

2020-03-07 02:15 UTC, ClayMav requested changes

2020-03-07 02:15 UTC, ClayMav commented on flight/utils/Wrapped_LAC.py
> +      raise Exception("Extend is set to the mechanical stop.")
move these above everything else in the function

2020-03-07 02:37 UTC, ClayMav approved these changes
codacy has a few issues you should fix but I am satisfied once she is

2020-03-09 16:13 UTC, merged