Feature/manual takeoff
MissouriMRR/IARC-2020 pull request #174
Opened 2020-03-20 01:11 UTC by acbk2b

Closes #168

2020-03-21 23:49 UTC, ClayMav requested changes
A few things:
- I think you should have an optional parameter to specify a tuple of (lat, lon) to go towards, so that we can still use takeoff as a simple vertical takeoff if that is not specified.
- The function takeoff should be in a different file, likely within `flight/utils`, so that it can be used other places if required.
- takeoff should also encapsulate all of the setting of set points and starting offboard
- I think you should rebase onto feature/gps_offset so you can use the LatLon library to simplify your math and logic
- I'm going to start enforcing type hints more closely, so make sure to specify function return types

2020-03-21 23:49 UTC, ClayMav commented on flight/states/takeoff.py
> +    async def takeoff(self, drone: System) -> None:
Specify in a docstring that this function assumes the drone is armed

2020-03-21 23:49 UTC, ClayMav commented on flight/states/takeoff.py
> +        up_speed: float = -2
This should be a file constant, not inside the function

2020-03-21 23:49 UTC, ClayMav commented on flight/states/takeoff.py
> +            if await self.wait_alt(drone) == True:
if wait_alt doesnt return True, then the drone will be in pieces, so dont use it as an if statement, just say
```python
await self.wait_alt(drone)
other_code_that_happens_after()
```

2020-03-21 23:49 UTC, ClayMav commented on flight/states/takeoff.py
> +                return True
If it can't return False, just have it return

2020-03-21 23:49 UTC, ClayMav commented on flight/states/takeoff.py
> +        up_speed: float = -2
Also its an int

2020-03-27 03:45 UTC, ClayMav requested changes
Very few things are wrong with this in its current state but itll get effed when we merge the gps_offset stuff

2020-03-27 03:45 UTC, ClayMav commented on flight/states/early_laps.py
>          """Goes to a position"""
wait_pos is still in this file

2020-03-27 03:45 UTC, ClayMav commented on flight/states/early_laps.py
>          """Completes a full turn"""
wait turn is still in here

2020-03-27 03:45 UTC, ClayMav commented on flight/utils/drone_takeoff.py
> +async def getPosition(drone: System, target_lat: float, target_lon: float):
```suggestion
async def get_distance(drone: System, target_lat: float, target_lon: float):
```

2020-03-27 03:45 UTC, ClayMav commented on flight/utils/drone_takeoff.py
> +async def getVelocity(drone: System, target_lat: float, target_lon: float):
```suggestion
async def get_velocity(drone: System, target_lat: float, target_lon: float):
```

2020-03-31 22:07 UTC, ClayMav reviewed
https://stackoverflow.com/questions/46497578/while-loop-blocks-asyncio-tasks

2020-11-18 02:23 UTC, closed without merging

2020-11-18 02:23 UTC, ewad3 commented
Outdated