Very simple manual takeoff function that replaces the built-in takeoff
MissouriMRR/IARC-2020 pull request #195
Opened 2020-10-22 22:08 UTC by JakeLockey

Made a function in the takeoff.py file called "takeoff", it runs after the configuration for manual control is done. All it does is set the velocity to be 1.0 upwards, and then uses the wait_alt function to stop at some altitude defined by variable "alt". After the takeoff function completes, it goes to the early_laps file, where the first wait_pos sends the drone to the first pylon.

2020-10-22 23:57 UTC, ewad3 commented
The takeoff function should only have drone and not the alt. The variable alt should be a constant in config.py replacing TAKEOFF_ALT with some flying altitude constant and using that new flying altitude constant in the respective math needed.

2020-10-23 00:32 UTC, pieperm requested changes

2020-10-23 00:32 UTC, pieperm commented on flight/states/takeoff.py
> +    async def takeoff(self, drone: (System)):
Remove redundant parentheses

2020-10-23 00:32 UTC, pieperm commented on flight/states/takeoff.py
>          return EarlyLaps()  # Return the next state, RunLaps
Might as well change this comment to say EarlyLaps instead of RunLaps

2020-10-23 00:46 UTC, pieperm approved these changes

2020-10-23 00:47 UTC, ewad3 approved these changes

2020-10-23 00:48 UTC, merged