created mast state and added a pause before landing
MissouriMRR/IARC-2020 pull request #208
Opened 2020-11-18 01:51 UTC by noahklein00

Added a new state to the __init__.py file called "mast". After completing "early_laps" state, this sends the drone to the "mast" location from the config.py file, sleeps for 20 seconds, then lands.

2020-11-18 02:20 UTC, ewad3 requested changes
Over all looks good just a few things to change and consider.

2020-11-18 02:20 UTC, ewad3 commented on flight/states/mast.py
> +class Mast:
The class mast should be a child class of state, this also requires importing state. ex: class Mast(State):

2020-11-18 02:20 UTC, ewad3 commented on flight/states/early_laps.py
>  from .land import Land
Remove Land if it is not in use.

2020-11-18 02:20 UTC, ewad3 commented on flight/states/early_laps.py
> +        #return Land()
Remove Land if it is not in use.

2020-11-18 02:20 UTC, ewad3 commented on flight/config.py
> +mast2: Longitude = Longitude(degree=-91, minute=-47, second=-5.0)
The naming of these don't make much sense.

2020-11-18 02:20 UTC, ewad3 commented on flight/config.py
> +MAX_SPEED: float = 15  # m/s
Understand increasing speed for testing but for merging leave as default.

2020-11-18 02:20 UTC, ewad3 commented on flight/config.py
> +NUM_LAPS: int = 1
Same as the speed leave as default for merging.

2020-11-18 02:20 UTC, ewad3 commented on flight/config.py
> +    return
Leave default for merging.

2020-11-18 02:20 UTC, ewad3 commented on flight/states/mast.py
> +        await mover.move_to(drone, config.mast)
Note about move_to function it fly's to an offset point to the right and not to the intended point. Not your fault but something to consider. May want to look into setting offset based off of a boolean.

2020-11-20 01:12 UTC, ewad3 submitted a review, later dismissed
Looks ready for a flight test.

2020-11-20 04:51 UTC, pieperm approved these changes

2020-11-20 04:51 UTC, merged